//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenProject.Infrastructure.Data.Entity
{
    using System;
    using BenProject.Core.Model;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BenedictProjectEntities : DbContext
    {
        public BenedictProjectEntities()
            : base("name=BenedictProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Family> Families { get; set; }
        public virtual DbSet<Individual> Individuals { get; set; }
    }
}
