//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenProject.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Individual
    {
        public int IndividualID { get; set; }
        public string Name { get; set; }
        public Nullable<int> FamilyID { get; set; }
        public Nullable<bool> Gender { get; set; }
    
        public virtual Family Family { get; set; }
    }
}
